# Generated by Django 4.0.4 on 2022-05-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False, verbose_name='ВЫполнено'),
        ),
    ]
