# Generated by Django 4.0.4 on 2022-05-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_person_todo_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='is_done',
        ),
    ]
